#########################################
#
# web访问端口号 约定：8088
#########################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

#########################################
#
# 配置数据源信息
#########################################
spring:
  datasource:                                              # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource               # 数据源类型HikariCP
    driver-class-name: com.mysql.jdbc.Driver               # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=True&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

##########################################
#
# mybatis 配置
#
##########################################
mybatis:
  type-aliases-package: com.dandan.pojo
  mapper-locations: classpath:mapper/*.xml

##########################################
#
# mybatis mapper配置
#
##########################################
# 通用Mapper设置
mapper:
  mappers: com.dandan.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL